// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCFt3hkI6YOpFJeoYxZlKfpDuelMaaK_Q',
    appId: '1:391956643298:web:51e5227be0d692b482cdbb',
    messagingSenderId: '391956643298',
    projectId: 'iskcon-vkhill-nitya-seva',
    authDomain: 'iskcon-vkhill-nitya-seva.firebaseapp.com',
    storageBucket: 'iskcon-vkhill-nitya-seva.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyCyVTQvWs2KfOTa3h-3vitCJxiMqmXNA',
    appId: '1:391956643298:android:859e793cd6d8d9e082cdbb',
    messagingSenderId: '391956643298',
    projectId: 'iskcon-vkhill-nitya-seva',
    storageBucket: 'iskcon-vkhill-nitya-seva.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADh6WyaIsxCoJIcX0NF3Mt-cA3EP7kYf0',
    appId: '1:391956643298:ios:2d5dc75c494ce66b82cdbb',
    messagingSenderId: '391956643298',
    projectId: 'iskcon-vkhill-nitya-seva',
    storageBucket: 'iskcon-vkhill-nitya-seva.appspot.com',
    iosBundleId: 'com.iskconvkhill.nityaSevaCalculation',
  );
}
